### ISSUE TITLE
Fix routing for page refresh

### ISSUE THREAD

**Issue by catalin-apostu** [it-pebune/ani-research-web#94]
Currently, when refreshing a page the routing leads to '/users' page, but it should stay on current page.

**Comment by endriu3314** [comment]
The issue comes from https://github.com/it-pebune/ani-research-web/blob/1609ca518b80de715031058b1704d72eb218dd55/src/App.tsx#L27-L35

I don't know what the intended use is, it looks like you want to redirect users after login? This could be better done by pushing to history using react-router or other ways.
